document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'Content-Language\' content=\'zh-CN\'/>");
document.writeln("    <link href=\'../css/main.css\'  rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("    <link href=\'../css/header.css\'  rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'main-head flex-row\'>");
document.writeln("        <div class=\'head-left\'>");
document.writeln("            <img src=\'../images/logo-33472c4d48.png\' alt=\'雷速体育\'>");
document.writeln("        </div>");
document.writeln("        <ul class=\'flex-row\'>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    首页");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'javascript:;\' target=\'_blank\'>");
document.writeln("                    即时比分");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    网球比分");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    赛事推荐");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    情报中心");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link active\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    资料库");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    彩票百科");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    数据服务");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    APP下载");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\'head-right\'>");
document.writeln("            <img src=\'\' alt=\'\'>");
document.writeln("            <span class=\'head-login\'>");
document.writeln("                登录");
document.writeln("            </span>");
document.writeln("            <span class=\'head-register active\'>");
document.writeln("                注册");
document.writeln("            </span>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html><!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'Content-Language\' content=\'zh-CN\'/>");
document.writeln("    <link href=\'../css/main.css\'  rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("    <link href=\'../css/header.css\'  rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'main-head flex-row\'>");
document.writeln("        <div class=\'head-left\'>");
document.writeln("            <img src=\'../images/logo-33472c4d48.png\' alt=\'雷速体育\'>");
document.writeln("        </div>");
document.writeln("        <ul class=\'flex-row\'>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    首页");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'javascript:;\' target=\'_blank\'>");
document.writeln("                    即时比分");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    网球比分");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    赛事推荐");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    情报中心");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link active\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    资料库");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    彩票百科");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    数据服务");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a class=\'nav-link\' href=\'http://www.cnblogs.com/jtjds/\' target=\'_blank\'>");
document.writeln("                    APP下载");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <div class=\'head-right\'>");
document.writeln("            <img src=\'\' alt=\'\'>");
document.writeln("            <span class=\'head-login\'>");
document.writeln("                登录");
document.writeln("            </span>");
document.writeln("            <span class=\'head-register active\'>");
document.writeln("                注册");
document.writeln("            </span>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");